# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40aff24c4639722d87c1356a96d8eb7f4142bc3145e951dd0ef6528bd41a1552001f0848b5b44790721bfcde7232183489dd9d0da80ddf1a7b4740cedfdc993b

test:
  secret_key_base: 2458679de187a0ac78269c58583119236ec43d3587d4f813332e93f90274dd9569cf41fd21dad3e0f8663d3ec0d4397b94121d852d4bcbeb5d93b5c0024f586b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
